
import { Country } from './types';

export const APP_NAME = "Golden Bank";
export const CURRENCY = "€";

// Mock admin credentials for demo
export const ADMIN_EMAIL = "admin@goldenbank.com";
export const ADMIN_PASSWORD = "admin"; // In a real app, never do this.

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪' },
  { code: 'AD', name: 'Andorre', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarctique', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua-et-Barbuda', flag: '🇦🇬' },
  { code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷' },
  { code: 'AM', name: 'Arménie', flag: '🇦🇲' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼' },
  { code: 'AU', name: 'Australie', flag: '🇦🇺' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaïdjan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermudes', flag: '🇧🇲' },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾' },
  { code: 'MM', name: 'Birmanie', flag: '🇲🇲' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳' },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo-Brazzaville', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo-Kinshasa', flag: '🇨🇩' },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominique', flag: '🇩🇲' },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬' },
  { code: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪' },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲' },
  { code: 'GE', name: 'Géorgie', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷' },
  { code: 'GD', name: 'Grenade', flag: '🇬🇩' },
  { code: 'GL', name: 'Groenland', flag: '🇬🇱' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GG', name: 'Guernesey', flag: '🇬🇬' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'GF', name: 'Guyane française', flag: '🇬🇫' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺' },
  { code: 'IM', name: 'Île de Man', flag: '🇮🇲' },
  { code: 'CX', name: 'Île Christmas', flag: '🇨🇽' },
  { code: 'NF', name: 'Île Norfolk', flag: '🇳🇫' },
  { code: 'AX', name: 'Îles Åland', flag: '🇦🇽' },
  { code: 'KY', name: 'Îles Caïmans', flag: '🇰🇾' },
  { code: 'CC', name: 'Îles Cocos', flag: '🇨🇨' },
  { code: 'CK', name: 'Îles Cook', flag: '🇨🇰' },
  { code: 'FO', name: 'Îles Féroé', flag: '🇫🇴' },
  { code: 'FK', name: 'Îles Malouines', flag: '🇫🇰' },
  { code: 'MP', name: 'Îles Mariannes du Nord', flag: '🇲🇵' },
  { code: 'MH', name: 'Îles Marshall', flag: '🇲🇭' },
  { code: 'PN', name: 'Îles Pitcairn', flag: '🇵🇳' },
  { code: 'SB', name: 'Îles Salomon', flag: '🇸🇧' },
  { code: 'TC', name: 'Îles Turques-et-Caïques', flag: '🇹🇨' },
  { code: 'VG', name: 'Îles Vierges britanniques', flag: '🇻🇬' },
  { code: 'VI', name: 'Îles Vierges des États-Unis', flag: '🇻🇮' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪' },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴' },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malte', flag: '🇲🇹' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronésie', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳' },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Népal', flag: '🇳🇵' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴' },
  { code: 'NC', name: 'Nouvelle-Calédonie', flag: '🇳🇨' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬' },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱' },
  { code: 'PF', name: 'Polynésie française', flag: '🇵🇫' },
  { code: 'PR', name: 'Porto Rico', flag: '🇵🇷' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪' },
  { code: 'DO', name: 'République dominicaine', flag: '🇩🇴' },
  { code: 'CZ', name: 'République tchèque', flag: '🇨🇿' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'EH', name: 'Sahara occidental', flag: '🇪🇭' },
  { code: 'BL', name: 'Saint-Barthélemy', flag: '🇧🇱' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', flag: '🇰🇳' },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲' },
  { code: 'MF', name: 'Saint-Martin (partie française)', flag: '🇲🇫' },
  { code: 'SX', name: 'Saint-Martin (partie néerlandaise)', flag: '🇸🇽' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', flag: '🇵🇲' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨' },
  { code: 'SH', name: 'Sainte-Hélène', flag: '🇸🇭' },
  { code: 'LC', name: 'Sainte-Lucie', flag: '🇱🇨' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'AS', name: 'Samoa américaines', flag: '🇦🇸' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen', flag: '🇸🇯' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾' },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯' },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'TF', name: 'Terres australes françaises', flag: '🇹🇫' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor oriental', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'Vatican', flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'WF', name: 'Wallis-et-Futuna', flag: '🇼🇫' },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
].sort((a, b) => a.name.localeCompare(b.name));

export const NAV_LINKS = [
  { label: 'Accueil', view: 'LANDING' },
  { label: 'À Propos', view: 'ABOUT' },
  { label: 'Services', view: 'SERVICES' },
  { label: 'Tarifs', view: 'PRICING' },
  { label: 'Contact', view: 'CONTACT' },
];

export const MOCK_ADMIN_USER: any = {
  id: 'admin-001',
  name: 'Super Administrator',
  email: ADMIN_EMAIL,
  role: 'ADMIN',
  balance: 999999999,
  avatarUrl: 'https://picsum.photos/200/200',
  accountType: 'CURRENT',
  cardNumber: '0000 0000 0000 0000',
  cardExpiry: '12/99',
  cardCVC: '000',
  joinedDate: new Date().toISOString(),
  birthDate: '1980-01-01',
  phone: '+33 6 00 00 00 00',
  address: 'Admin HQ',
  postalCode: '75000',
  country: COUNTRIES.find(c => c.code === 'FR') || COUNTRIES[0],
  password: ADMIN_PASSWORD
};

// STOCK MARKET CONSTANTS
export const COMPETITORS = [
  { name: 'JP Morgan', symbol: 'JPM', price: 140.50, domain: 'jpmorganchase.com' },
  { name: 'Bank of America', symbol: 'BAC', price: 34.20, domain: 'bankofamerica.com' },
  { name: 'Wells Fargo', symbol: 'WFC', price: 42.80, domain: 'wellsfargo.com' },
  { name: 'HSBC Holdings', symbol: 'HSBC', price: 38.90, domain: 'hsbc.com' },
  { name: 'Citigroup', symbol: 'C', price: 48.10, domain: 'citigroup.com' },
  { name: 'BNP Paribas', symbol: 'BNP', price: 62.40, domain: 'group.bnpparibas' },
  { name: 'Santander', symbol: 'SAN', price: 3.80, domain: 'santander.com' },
  { name: 'Goldman Sachs', symbol: 'GS', price: 340.00, domain: 'goldmansachs.com' },
  { name: 'UBS Group', symbol: 'UBS', price: 28.50, domain: 'ubs.com' },
  { name: 'Barclays', symbol: 'BCS', price: 8.90, domain: 'barclays.co.uk' },
  { name: 'Deutsche Bank', symbol: 'DB', price: 11.20, domain: 'db.com' },
  { name: 'Morgan Stanley', symbol: 'MS', price: 92.30, domain: 'morganstanley.com' },
  { name: 'Credit Agricole', symbol: 'ACA', price: 12.40, domain: 'credit-agricole.com' },
  { name: 'Societe Generale', symbol: 'GLE', price: 24.80, domain: 'societegenerale.com' },
  { name: 'ING Group', symbol: 'ING', price: 13.50, domain: 'ing.com' },
  { name: 'NatWest', symbol: 'NWG', price: 7.20, domain: 'natwestgroup.com' },
  { name: 'Standard Chartered', symbol: 'STAN', price: 9.50, domain: 'sc.com' },
  { name: 'AXA Bank', symbol: 'AXA', price: 28.85, domain: 'axa.com' },
  { name: 'Mizuho', symbol: 'MFG', price: 2.90, domain: 'mizuhogroup.com' },
  { name: 'RBC', symbol: 'RY', price: 98.10, domain: 'rbc.com' },
];

export const FAILING_BANKS = [
  { name: 'DinoBank Inc.', symbol: 'DINO', price: 850.00, letter: 'D' },
  { name: 'OldGuard Fin', symbol: 'OLD', price: 420.50, letter: 'O' },
  { name: 'RustyVault', symbol: 'RUST', price: 150.20, letter: 'R' },
  { name: 'SlowCapital', symbol: 'SLOW', price: 95.00, letter: 'S' },
  { name: 'LegacyTrust', symbol: 'LGCY', price: 600.10, letter: 'L' },
  { name: 'FossilBank', symbol: 'FOSL', price: 310.40, letter: 'F' },
  { name: 'StoneAge Ltd', symbol: 'ROCK', price: 50.75, letter: 'S' },
  { name: 'Cobweb Corp', symbol: 'DUST', price: 25.00, letter: 'C' },
];
