

export type UserRole = 'USER' | 'ADMIN';
export type AccountType = 'CURRENT' | 'SAVINGS';
export type LanguageCode = 'fr' | 'en' | 'es' | 'de' | 'it' | 'pt' | 'nl' | 'ru' | 'zh' | 'ja' | 'ar';

export interface Country {
  code: string;
  name: string;
  flag: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  balance: number;
  avatarUrl: string;
  
  // Banking Info
  accountType: AccountType;
  cardNumber: string;
  cardExpiry: string;
  cardCVC: string;
  joinedDate: string;
  
  // Personal Info
  birthDate: string;
  phone: string;
  
  // Address
  address: string;
  postalCode: string;
  country: Country;
  
  // Security
  password?: string; // In a real app, this would be hashed
}

export interface Transaction {
  id: string;
  userId: string; // The account owner associated with this log
  type: 'CREDIT' | 'DEBIT'; // Direction of money
  recipientName: string; // For DEBIT: Receiver. For CREDIT: Sender/Source.
  recipientBank: string;
  recipientIban: string;
  amount: number;
  date: string;
  status: 'PENDING' | 'COMPLETED' | 'FAILED';
}

export interface AdminLog {
  id: string;
  adminName: string;
  actionType: 'BALANCE_UPDATE' | 'USER_DELETION' | 'SYSTEM';
  targetUserName: string;
  description: string;
  timestamp: string;
}

// Complex transaction state for the "Live Progress" feature
export interface ActiveTransfer {
  userId?: string; // ID of the user performing the transfer
  isActive: boolean;
  progress: number; // 0 to 100
  isPaused: boolean;
  requiredCode: string | null; // The code generated by admin system
  recipientName: string;
  amount: number;
  currentStepDescription: string;
  completed?: boolean;
}

export interface Message {
  id: string;
  senderId: string; // 'ADMIN' or userId
  receiverId: string; // 'ADMIN' or userId
  content: string;
  timestamp: string;
  isRead: boolean;
}

export interface AdminChatSettings {
  showReadReceiptsToUser: boolean; // Does the user see that admin read the msg?
  showTypingToUser: boolean; // Does the user see that admin is typing?
  showOnlineStatusToUser: boolean; // Does the user see that admin is online?
}

// Market Data Types
export interface MarketStock {
  name: string;
  symbol: string;
  price: number;
  change: number;
  trend: 'up' | 'down' | 'neutral';
  domain: string;
}

export interface FailingBankData {
  name: string;
  symbol: string;
  price: number;
  letter: string;
}

export interface MarketState {
  novaPrice: number;
  novaHistory: number[];
  failingBank: FailingBankData;
  competitorPrice: number;
  competitorHistory: number[];
  marketData: MarketStock[];
}

export type ViewState = 'LANDING' | 'LOGIN' | 'REGISTER' | 'DASHBOARD' | 'ADMIN' | 'ABOUT' | 'SERVICES' | 'PRICING' | 'CONTACT' | 'LEGAL' | 'PRIVACY' | 'COOKIES';